#!/usr/bin/env bash

if [[ `whoami` != "root" ]]; then
    echo "You must be root to run this installer."
    exit 1
fi

packages=([0]="tornado" [1]="python-mpd")

function isInstalled () {
    pip freeze | grep $1 > /dev/null
    return $?
}


which pip > /dev/null
if [[ $? -ne 0 ]]; then
    echo "Installing pip..."
    wget pypi.python.org/packages/source/p/pip/pip-1.2.1.tar.gz
    tar -xf pip-1.2.1.tar.gz
    cd pip-1.2.1
    python setup.py install
    cd ..
    rm -r pip-1.2.1*
else
    echo "pip is already installed."
fi

for i in 0 1; do
    var=`isInstalled ${packages[$i]}`
    if [[ var -ne 0 ]]; then
        echo "Installing package ${packages[$i]}..."
        pip install $package
    else
        echo "Package ${packages[$i]} is already installed."
    fi
done

exit 0