#!/usr/bin/env bash

# Ensure script is being run as root
if [[ `whoami` != "root" ]]; then
    echo "You must be root to run this installer."
    exit 1
fi

# Check whether pip is installed
# Download and install pip if necessary
which pip > /dev/null
if [[ $? -ne 0 ]]; then
    echo "Installing pip..."
    wget pypi.python.org/packages/source/p/pip/pip-1.2.1.tar.gz
    tar -xf pip-1.2.1.tar.gz
    cd pip-1.2.1
    python setup.py install
    cd ..
    rm -r pip-1.2.1*
else
    echo "pip is already installed."
fi

# Check whether the packages in the package list are installed
# Install any missing packages through pip
packages=([0]="tornado" [1]="python-mpd")
for p in ${packages[@]}; do
    pip freeze | grep $p > /dev/null
    if [[ $? -ne 0 ]]; then
        echo "Installing package $p..."
        pip install $package
    else
        echo "Package $p is already installed."
    fi
done

exit 0
